tls_test_01:clean
	gcc -g -O0 -std=c99 tls_test_01.c -o tls_test_01  -lpthread
	./tls_test_01
tls_test_02:clean
	gcc -g -O0 -std=c99 tls_test_02.c -o tls_test_02  -lpthread
	./tls_test_02
arch_prctl_test:clean
	gcc -g -O0 -std=c99 arch_prctl_test.c -o arch_prctl_test
clean:
	rm -f ./tls_test_01